### ISSUE TITLE
[BUG] A Lost Notch

### ISSUE THREAD

**Issue by oleajan** [TheBoredTeam/boring.notch#219]
**Describe the bug**
Notch placed in random place when connecting to external monitor while lid is closed.

**To Reproduce**
1. Connect your macbook pro on an external monitor while the lid is closed

**Expected behavior**
Notch to placed on the notch

**Screenshots or recordings**
![Screenshot 2024-11-20 at 6 38 36 PM](https://github.com/user-attachments/assets/e34b92ea-747d-4e6b-bc91-d2155f811f0f)

**Additional context**
I use an MBP M3 Pro 14' MacOS 15.1.1
External Monitor is a Xiaomi 34' ultrawide
BetterDisplay App is set to HiDpi mode at 3440x1440
BoringNotch v2.3

**Comment by oleajan** [comment]
Edit: sorry. That should be MacOS 15.1.1

**Comment by jamesdoc** [comment]
I've also encountered this issue when going from mirroring a display and then unplugging the external display. Resetting does resolve the issue.

<img width="1077" alt="Screenshot 2024-11-23 at 20 28 06" src="https://github.com/user-attachments/assets/b7b519f6-bbf3-4b41-892f-6cd1a719e06a">

**Comment by Alexander5015** [comment]
This has been fixed in the `dev` branch by #221 and will be included in our next release.

**Comment by ayan-binish** [comment]
It happened to me too: 
![image](https://github.com/user-attachments/assets/c017cffe-165d-4cfe-9d67-ac41853da276)

**Comment by FormalSnake** [comment]
Is there an estimate as to when this fix will be released? It is very annoying

**Comment by Leon-ok** [comment]
Hello, I updated to the last version (2.5) but this bug is still happening to me! It is quite inconvenient having to restart the app each time my external monitor wakes up (connected to a mac mini m4).

**Comment by FormalSnake** [comment]
I also still have the issue, just less frequently or with a lesser offset. My external monitor gets the norch correctly but the inner display (m1) gets the notch off screen
